#!/usr/bin/env python3
"""broken_marker_gate.py — deterministic "incomplete-deliverable marker" detector.

NON-safety ADVISORY lint (same stance as visual_slop_gate): fail-OPEN, surfaces findings to the
model so it can finish them or consciously keep them; NEVER hard-blocks. It is the mechanical teeth
for the kit's existing "prove it's done / no stub passed off as done" axiom — it catches the markers
a model leaves when it ships a skeleton while reporting complete.

Design rationale (ship, but trim hard):
  - Scan the ADDED content from this write (Write.content / Edit.new_string / MultiEdit.edits[].new_string),
    NOT the whole post-write file — otherwise a pre-existing legitimate TODO re-surfaces on every
    unrelated edit. The wrapper pipes the added strings on stdin; --hook takes file_path as arg (for
    the extension / path-exclusion / generated-header guards only).
  - HIGH-PRECISION markers ONLY (an unimplemented runtime body, an unfilled literal placeholder, lorem
    ipsum). Bare TODO/FIXME/XXX/HACK are CUT in v1 (backlog conventions, not incomplete deliverables).
  - Heavy path / file-type / generated-header exclusions (tests, fixtures, templates, vendor,
    generated, docs, config samples) — markers are legitimate there.
  - Advisory PostToolUse additionalContext, per-write, stateless, fail-open. Not a Stop gate.

CLI:
  python broken_marker_gate.py <file>            # human report on the whole file; exit 1 if findings
  python broken_marker_gate.py --hook <file>     # scan stdin (added content); advisory JSON; ALWAYS exit 0
"""
import sys, os, re

MAX_BYTES = 600_000

CODE_EXT = {".js", ".jsx", ".ts", ".tsx", ".py", ".go", ".rs", ".java", ".kt", ".cs", ".rb",
            ".php", ".c", ".cc", ".cpp", ".h", ".hpp", ".sh", ".bash", ".zsh", ".ps1"}
CAUTIOUS_EXT = {".html", ".css", ".scss", ".vue", ".svelte", ".astro"}   # user-visible shipped content
SCAN_EXT = CODE_EXT | CAUTIOUS_EXT   # .md/.mdx/.txt/.json/.yaml/.yml excluded by default

# paths where markers are legitimate (tests, fixtures, templates, vendor, generated, samples)
EXCL_PATH = re.compile(
    r'(^|[/\\])(tests?|specs?|__tests__|fixtures?|fixture|mocks?|mock|examples?|example|demo|'
    r'templates?|template|scaffold|vendor|node_modules|dist|build|\.next|coverage|generated)([/\\]|$)'
    r'|\.(test|spec|stories|fixture|mock)\.'
    r'|\.env\.(example|template|sample)', re.I)

GENERATED_HEADER = re.compile(r'auto-generated|generated by|do not edit|@generated', re.I)

# HIGH-precision incomplete-deliverable markers (trimmed set).
HIGH_PATTERNS = [
    ("unimplemented-runtime", re.compile(
        r'\braise\s+NotImplementedError\b'
        r'|\bNotImplementedError\b'
        r'|throw\s+new\s+\w*Error\s*\(\s*["\'`][^"\'`]*\b(?:not[\s_-]*implemented|unimplemented|todo)\b'
        r'|UnsupportedOperationException\s*\(\s*["\'`][^"\'`]*\b(?:not[\s_-]*implemented|todo)\b'
        r'|\bunimplemented!\s*\('
        r'|\btodo!\s*\('
        r'|\bpanic!\s*\(\s*["\'`][^"\'`]*\b(?:todo|not[\s_-]*implemented|unimplemented)\b'
        r'|\bpanic\s*\(\s*["\'`][^"\'`]*\b(?:TODO|not[\s_-]*implemented)\b', re.I)),
    ("placeholder-text", re.compile(
        r'\b(?:your\s+code\s+here|implement\s+me|replace\s+this|add\s+your\s+code\s+here'
        r'|insert\s+\w+\s+here|fill\s+this\s+in)\b', re.I)),
    ("bracket-placeholder", re.compile(
        r'\[(?:your\s+\w+|insert\s+[^\]\n]{1,40}|replace\s+this|TODO|FIXME|placeholder|'
        r'fill[\s_-]?in[^\]\n]{0,30})\]', re.I)),
    ("lorem-ipsum", re.compile(r'\blorem\s+ipsum\b', re.I)),
    ("stub-body", re.compile(
        r'def\s+\w+\s*\([^)]*\)[^:]*:\s*(?:pass|\.\.\.)\s*#\s*(?:todo|implement|not[\s_-]*implemented|stub)',
        re.I)),
]


def scan_text(text):
    findings = []
    for key, pat in HIGH_PATTERNS:
        n = len(pat.findall(text))
        if n:
            findings.append((key, n))
    return findings


def _path_ok(path):
    if os.path.splitext(path)[1].lower() not in SCAN_EXT:
        return False
    if EXCL_PATH.search(path):
        return False
    return True


def _is_generated(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            head = fh.read(2000)
        return bool(GENERATED_HEADER.search(head))
    except Exception:
        return False


def format_advisory(path, findings):
    lines = [f"broken-marker lint — possible incomplete-deliverable marker(s) in "
             f"{os.path.basename(path)} (awareness, NOT a block — judge against intent):"]
    desc = {
        "unimplemented-runtime": "an unimplemented runtime body (NotImplementedError / throw-not-implemented / todo!() / panic-todo)",
        "placeholder-text": "literal placeholder copy ('your code here' / 'replace this' / 'implement me')",
        "bracket-placeholder": "an unfilled [bracket] placeholder",
        "lorem-ipsum": "lorem ipsum filler in shipped content",
        "stub-body": "a stubbed function body explicitly marked TODO/implement",
    }
    for key, n in findings:
        lines.append(f"  [{n}x] {key}: {desc.get(key, key)}")
    lines.append("  If you reported this complete, these contradict that — finish them, or say what is "
                 "BLOCKED and why. A marker you are deliberately keeping (a real backlog note) is fine.")
    return "\n".join(lines)


def main(argv):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    hook = False
    args = list(argv[1:])
    if args and args[0] == "--hook":
        hook = True
        args = args[1:]
    if not args:
        sys.stderr.write("usage: broken_marker_gate.py [--hook] <file>\n")
        return 0
    path = args[0]
    if not _path_ok(path):
        return 0
    if _is_generated(path):
        return 0
    if hook:
        text = sys.stdin.read()            # the ADDED content piped by the wrapper
    else:
        try:
            if os.path.getsize(path) > MAX_BYTES:
                return 0
            with open(path, encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except Exception:
            return 0
    if not text.strip():
        return 0
    try:
        findings = scan_text(text)
    except Exception as e:
        sys.stderr.write(f"broken-marker lint: internal error ({e}); fail-open\n")
        return 0
    if hook:
        if findings:
            import json as _json
            payload = {"hookSpecificOutput": {"hookEventName": "PostToolUse",
                                              "additionalContext": format_advisory(path, findings)}}
            sys.stdout.write(_json.dumps(payload, ensure_ascii=False))
        return 0
    if not findings:
        print(f"broken-marker lint: clean — {path}")
        return 0
    print(format_advisory(path, findings))
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
